platform :ios, '8.0'
inhibit_all_warnings!

target 'iOSSizeClasses' do
     pod 'Masonry'
     #pod 'Charts'
           #友盟分享UShare
           #pod 'UMengUShare/UI'
           #pod 'UMengUShare/Social/WeChat'
           # 加入IDFA获取
           #pod 'UMengUShare/Plugin/IDFA'
end

