platform :ios, '8.0'
inhibit_all_warnings!


flutter_application_path = '../my_flutter/'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'iOSSizeClasses' do
    
     pod 'Masonry'
     pod 'AFNetworking'
     pod 'MJRefresh'
     pod 'JLRoutes'

     install_all_flutter_pods(flutter_application_path)

end
